packages/pychromVAR/meta.yaml
Name of the tool: pychromVAR
Short description: A python package for chromVAR
How does the package use scverse data structures (please describe in a few sentences): 
The package uses Anndata and Mudata for estimating motifs binding sites accessibility deviations from scATAC-seq.
-   [x] The package provides API documentation via a website or README
-   [x] The package uses scverse datastructures where appropriate (i.e.anndata/mudata and …
=> add pychromVAR

packages/PyDESeq2/meta.yaml
*Name of the tool:* PyDESeq2
*Short description:* PyDESeq2 is a python package for bulk RNA-seq differential expression analysis. It is a re-implementation from scratch of the main features of the R package DESeq2 (Love et al. 2014).
*How does the package use scverse data structures (please describe in a few sentences):* PyDESeq2 does its heavy lifting using the `DeseqDataSet` class, which extends `AnnData`. In particular, read counts are stored in the `X` attribute, clinical metadata in `obs` and learned parameters in the relevant `varm` or `obsm` fields.
-   [x] The package can be installed from a standard registry (e.g. …
=> Add PyDESeq2

packages/symphonypy/meta.yaml
Name of the tool: symphonypy
Short description: Python port of Symphony label transfer algorithm for reference-based cell type annotation.
How does the package use scverse data structures (please describe in a few sentences): it's fully integrated in standard scanpy-based single-cell RNA-Seq processing pipeline and uses AnnData containers for all of the data manipulations.
+ The code is publicly available under an [OSI-approved](https://opensource.org/licenses/alphabetical) license
+ The package provides versioned releases
+ The package can be installed from a standard registry (e.g. PyPI, conda-forge, bioconda)
+ The package uses automated software tests and runs them via continuous integration (CI)
+ The package provides API documentation via a website or README
+ The package uses …
=> add symphonypy package

packages/scyan/meta.yaml
Name of the tool: `scyan`
Short description: Scyan is a biology-driven deep generative model (more precisely, a normalizing flow) for cell-type annotation in **cytometry**. It is an interpretable model that also corrects batch-effect and can be used for debarcoding or population discovery.
How does the package use scverse data structures (please describe in a few sentences): it is entirely based on `anndata` (for users that are not used to `anndata`, we have `.FCS` readers that makes `anndata` objects). The package design is also similar to `scanpy` (e.g., `scyan.plot` or `scyan.tools`). NB: as `scanpy` is not meant for cytometry, it is not a dependency of `scyan`, but we re-use only one function of scanpy (we mentioned in a README and in a comment that it was copied from scanpy).
-   [x] …
=> adding scyan meta.yml file

affiliated/scverse_affiliated_package_review_guidelines.md
=> Scverse affiliated packages review guidelines

packages/sopa/meta.yaml
Name of the tool: `sopa`
Short description: Sopa enables processing and analyses of image-based spatial-omics using a standard data structure and output. We currently support the following technologies: Xenium, MERSCOPE, CosMX, PhenoCycler, MACSIMA, Hyperion. Sopa was designed for generability and low-memory consumption on large images (scales to 1TB+ images). The pipeline outputs contain: (i) Xenium Explorer files for interactive visualization, (ii) a HTML report for quick quality controls, and (iii) a SpatialData `.zarr` directory for further analyses.
How does the package use scverse data structures (please describe in a few sentences): `sopa` is built on top of `spatialdata`, a recent scverse data structure. Sopa also has a great interoperability with packages such as `scanpy` or …
=> add sopa meta.yaml file

packages/panpipes/meta.yaml
Name of the tool: Panpipes
Short description: A pipeline for multiomic single-cell and spatial transcriptomic data analysis
How does the package use scverse data structures (please describe in a few sentences): XXX
-   [x] The package provides API documentation via a website or README
-   [x] The package uses scverse datastructures where appropriate (i.e. AnnData, MuData or SpatialData and their modality-specific extensions)
-   [x] I am …
=> add panpipes

packages/flowsom/meta.yaml
Name of the tool: FlowSOM
Short description: The complete FlowSOM package known from R, now available in Python!
Analyze high-dimensional cytometry data using FlowSOM, a clustering and visualization algorithm based on a self-organizing map (SOM). FlowSOM is used to distinguish cell populations from cytometry data in an unsupervised way and can help to gain deeper insights in fields such as immunology and oncology.
How does the package use scverse data structures (please describe in a few sentences): MuData is used to store cell clustering and metaclustering.
-   [x] The package can be installed from a standard registry (e.g. …
=> add flowsom meta.yaml

packages/palantir/meta.yaml
This PR is a submission of [palantir](https://github.com/dpeerlab/Palantir) to the scverse. Palantir is already part of `scanpy.external.tl`. However, since `scanpy.external` seems to be deprecated, and palantir is still being maintained, we would like to make this addition to the scversen to remain part of the ecosystem.
Name of the tool: palantir
Short description: Palantir is an algorithm to align cells along differentiation trajectories. Palantir models differentiation as a stochastic process where stem cells differentiate to terminally differentiated cells by a series of steps through a low dimensional phenotypic manifold. Palantir effectively captures the continuity in cell states and the stochasticity in cell fate determination. Palantir has been designed to work with …
=> Add palantir to the scverse

packages/pytximport/meta.yaml
Name of the tool: pytximport
Short description: `pytximport` is a Python port of the popular `tximport` Bioconductor package (unaffiliated with the `tximport` authors) and allows users to convert transcription level quantification files from pseudoalignment/quasi-mapping tools like `kallisto` and `salmon` to gene-level count estimates, thereby enabling the use of downstream gene differential expression analysis tools such as `PyDESeq2`. Depending on its configuration, `pytximport` corrects for differential transcript usage between samples, provides a length offset matrix for downstream correction, filters by transcript biotype or even returns corrected transcript-level data for differential transcript expression analysis.
How does the package use scverse data structures (please describe …
=> Add pytximport

packages/PILOT/meta.yaml
=> Add  PILOT

packages/GPTBioInsightor/meta.yaml
Name of the tool: GPTBioInsightor
Short description: GPTBioInsightor is a tool designed for single-cell data analysis, particularly beneficial for newcomers to a biological field or those in interdisciplinary areas who may lack sufficient biological background knowledge. GPTBioInsightor utilizes the powerful capabilities of large language models to help people quickly gain knowledge and insight, enhancing their work efficiency.
How does the package use scverse data structures (please describe in a few sentences): GPTBioInsightor uses AnnData object as input.
-   [x] The package can be installed from a standard registry (e.g. …
=> add GPTBioInsightor

packages/CellCharter/meta.yaml, template-repos.yml
Name of the tool: CellCharter
Short description: a framework to identify, characterize, and compare spatial domains from spatial omics and multi-omics data. 
How does the package use scverse data structures: it's based on AnnData and for some parts on SpatialData. It uses functions from Squidpy and Scanpy and the results are compatible with those packages.
-   [x] Automated tests cover essential functions of the package and a reasonable range of inputs and conditions
-   [x] Continuous integration (CI) automatically executes these …
=> add CellCharter

packages/vitessce/meta.yaml
The Vitessce package description didn't include "visual" and therefore was not findable for users searching for "visualization" etc.. Also updated the publication information and latest version.
=> Updated description, publications, and version information for Vitessce

packages/LazySlide/meta.yaml, packages/wsidata/meta.yaml
Name of the tool: wsidata
Short description: wsidata is a data-structure for efficient IO of Whole Slide Images based on spatialdata.
How does the package use scverse data structures (please describe in a few sentences): The wsidata extends SpatialData to tailor the usage for Whole Slide Imaging
- Twitter:
- Zulip:
- Discourse:
- Mastodon:
Name of the tool: LazySlide
Short description: LazySlide is a Python library for processing whole slide images (WSI) analysis. It provides a simple interface to perform robust preprocessing and advanced analysis for WSI.
How does the package use scverse data structures (please describe in a few sentences): LazySlide used previous described wsidata as data structures. Since wsidata is extended from SpatialData, many functions in LazySlide is also …
=> Add entries for wsidata and LazySlide

packages/spatialproteomics/meta.yaml
Name of the tool: spatialproteomics
Short description: Spatialproteomics is an interoperable toolbox for analyzing highly multiplexed fluorescence image data. This analysis involves a sequence of steps, including segmentation, image processing, marker quantification, cell type classification, and neighborhood analysis.
How does the package use scverse data structures (please describe in a few sentences): Spatialproteomics has a backend fully based on `spatialdata`. It also offers an alternative backend based on `xarray` (to enable synchronization of shared data dimensions beyond the current capabilities of `spatialdata`), from which users can export data into `anndata` or `spatialdata` format.
- Zulip: Matthias Meyer-Bender, Harald Voehringer
- Bluesky: @matthiasmeybe.bsky.social
- …
=> Added spatialproteomics

packages/PEAKQC/meta.yaml
Name of the tool: PEAKQC
Short description: Periodicity Evaluation in scATAC-seq data for quality assessment
How does the package use scverse data structures (please describe in a few sentences): 
The package can be used within a scanpy/episcanpy based pipeline to calculate per cell quality scores based on fragments provided by different file formats. The anndata format is used to read the barcode data and stores the results in the observables table. Scanpy functions can then be used to filter on the scores.
- Zulip:
- Discourse:
- Mastodon:
- Bluesky:
- Twitter: @loosolab
=> Add PEAKQC

packages/CellMapper/meta.yaml
Name of the tool: CellMapper
Short description: CellMapper is a leightweight tool to transfer labels, expression values and embeddings from reference to query datasets using k-NN mapping. It's fast and versatile, applicable to mapping scenarios in space, across modalities, or from an atlas to a new query dataset.
How does the package use scverse data structures (please describe in a few sentences): CellMapper uses AnnData to represent query and reference datasets throughout the package. 
- Zulip:
- Discourse:
- Mastodon:
- Bluesky: https://bsky.app/profile/mariuslange.bsky.social
- Twitter: https://x.com/MariusLange8
[^1]: We recommend thtat tests cover at least all user facing (public) functions. Minimal tests ensure that the function does not fail on an example data set. Ideally, tests …
=> Add CellMapper

packages/scCellFie/meta.yaml
Name of the tool: scCellFie
Short description: scCellFie is a Python tool for analyzing metabolic activity at different resolutions, developed at the [Vento Lab](https://ventolab.org/). It efficiently processes both single-cell and spatial data to predict metabolic task activities. Additionally, scCellFie offers downstream analyses such as marker selection, differential analysis, and cell-cell communication inference.
How does the package use scverse data structures (please describe in a few sentences): ``anndata`` is used as input (and output whenever appropriate); uses, ``squidpy``'s neighborhood graph format; and integrates ``scanpy``'s visualizations.
- Bluesky: @erickarmingol.bsky.social‬
- Twitter: @eagut; @roserventotormo
[^1]: We recommend thtat tests cover at least all user …
=> Add scCellFie

packages/spatiomic/meta.yaml
Name of the tool: spatiomic
Short description: `spatiomic` is a computational library for the analysis of spatial proteomics, mainly via pixel-based clustering, differential cluster abundance analysis and spatial statistics. It differs from existing implementations mostly by focussing on unsupervised subcellular analyses with GPU acceleration. For more information, please refer to our paper: https://www.nature.com/articles/s41586-025-09225-2 or the documentation at https://spatiomic.org
How does the package use scverse data structures (please describe in a few sentences): Currently, most common functions accept and write to AnnData objects and the library contains additional utility functions to easily convert between PySAL spatial weights and the format used for scverse packages. …
=> Add spatiomic

packages/scXpand/meta.yaml
Dear scverse team,
Please find below the complete checklist regarding adding our new package to your ecosystem: scXpand.
Thank you very much!
Ofir
Name of the tool: scXpand
Short description: scXpand is a machine learning framework for pan-cancer detection of T-cell clonal expansion directly from single-cell RNA sequencing (scRNA-seq), without paired T-cell receptor (TCR) sequencing.
How does the package use scverse data structures (please describe in a few sentences): Our package is fully compatible with AnnData as the standard data structure, and uses Scanpy and Scirpy as part of the data preparation procedures and downstream analysis.
Recommended
Zulip:
Discourse:
Mastodon:
Bluesky:
Twitter: `@OfirShorer`, `@RonAmit5`, `@YizhakLab`
=> Add scXpand

packages/pyUCell/meta.yaml
Name of the tool: pyUCell
Short description: pyUCell is a computational method for robust and scalable single-cell signature scoring. UCell signature scores, based on the Mann-Whitney U statistic, are robust to dataset size and heterogeneity, and their calculation is very fast and memory-efficient.
How does the package use scverse data structures (please describe in a few sentences): pyUCell relies on AnnData data structures and depends on scanpy. It can be integrated in existing scanpy pipelines and offers an alternative to `scanpy.tl.score_genes()`
- Zulip:
- Discourse:
- Mastodon:
- Bluesky: @carmonation.bsky.social
- Twitter: @carmonation
=> Add pyUCell
