README.md
=> Update readme w/ discourse + github org

packages/CellRank/meta.yaml
=> CellRank package

packages/SnapATAC2 /meta.yaml
=> SnapATAC2 package

packages/DoubletDetection/meta.yaml
=> DoubletDetection package

packages/cell2location/meta.yaml
=> cell2location package

packages/cellxgene/meta.yaml
=> cellxgene package

packages/Cell_BLAST/meta.yaml
=> Cell_BLAST package

packages/Cirrocumulus/meta.yaml
=> cirrocumulus package

packages/spatial-eggplant/meta.yaml
=> add spatial-eggplant

packages/bento-tools/meta.yaml
=> add bento tools

.github/workflows/make-json.yml
Concatenate all `meta.yaml` files into a single json array
=> Make JSON for website

README.md
=> Remove support statement

packages/scvelo/meta.yaml
@WeilerP, I'd like to include scvelo on our new ecosystem listing (check out the [pr](https://github.com/scverse/scverse.github.io/pull/70) and [preview](https://deploy-preview-70--jade-cajeta-1bcca0.netlify.app/projects).
Does this all look good to you?
--------
Name of the tool: scvelo
Short description: 
> scVelo is a scalable toolkit for RNA velocity analysis in single cells, based on Bergen et al. [(Nature Biotech, 2020)](https://doi.org/10.1038/s41587-020-0591-3).
How does the package use scverse data structures (please describe in a few sentences): Uses AnnData
-   [x] The package can be installed from a standard …
=> Add scvelo

packages/sfaira/meta.yaml
=> add sfaira package

packages/scGen/meta.yaml
=> add scGen package

packages/pySCENIC/meta.yaml
=> add pySCENIC package

packages/pegasus/meta.yaml
=> add Pegasus

packages/PathML/meta.yaml
=> add PathML package

README.md
=> Minor language change on CI requirement

packages/scFates/meta.yaml
_Name of the tool_: scFates
_Short description_: scFates provides an extensive toolset for the analysis of dynamic trajectories comprising tree learning, feature association testing, branch differential expression and with a focus on cell biasing and fate splits at the level of bifurcations. It is meant to be fully integrated into the scanpy ecosystem for seamless analysis of trajectories from single-cell data.
_How does the package use scverse data structures (please describe in a few sentences)_: scFates is fully integrated in scanpy ecosystem, as it uses anndata format as input, and its functions use and update `layers`/`obs`/`obsm`/`var`/`uns` fields for tree learning, branch and pseudotime assignment, expression GAM fitting and various statistical tests.
=> scFates package

.github/workflows/make-json.yml, packages/scvelo/meta.yaml
=> Add trigger request for page build

packages/hotspot/meta.yaml
Name of the tool: Hotspot
Short description: Hotspot is a tool for identifying informative genes (and gene modules) in a single-cell dataset.
How does the package use scverse data structures (please describe in a few sentences): Hotspot natively works with anndata
-   [x] The package provides API documentation via a website or README
-   [x] The package uses scverse datastructures where appropriate (i.e.anndata/mudata and their …
=> Add Hotspot

packages/Mowgli/meta.yaml
Name of the tool: Mowgli
Short description: Paired single-cell integration for multi-omics data, using Optimal Transport-flavored Nonnegative Matrix Factorization.
How does the package use scverse data structures (please describe in a few sentences): We use MuData objects to store multi-omics data. The embedding is stored in `obsm` and additional information in `uns`. Custom plotting and helper functions make use of Scanpy.
-   [x] The …
=> Add Mowgli

.pre-commit-config.yaml, packages/CellOracle/meta.yaml, packages/CellRank/meta.yaml, packages/DoubletDetection/meta.yaml, packages/cell2location/meta.yaml, packages/cellxgene/meta.yaml, packages/dynamo-release/meta.yaml, packages/epiScanpy/meta.yaml, packages/pySCENIC/meta.yaml, packages/scGen/meta.yaml, packages/vitessce/meta.yaml
=> Add default hooks from template

.github/workflows/register-template-repos.yml
=> Actually push changes when new repo is detected

packages/Multivelo/meta.yaml
Name of the tool: Multivelo
Short description: A mechanistic model of gene expression that extends the popular RNA velocity framework by incorporating epigenomic data.
How does the package use scverse data structures (please describe in a few sentences): Multivelo is designed to process data stored in AnnData objects. In addition, it uses Scanpy tools in order to process the data at various steps in our functions.
=> Request to add Multivelo to scverse

packages/maxspin/meta.yaml
Name of the tool: maxspin
Short description: An information theoretic measurement of spatial organization, serving as a more general, sensitive, and interpretable alternative to traditional spatial (auto)correlation measures and SVG tests.
How does the package use scverse data structures (please describe in a few sentences): The method operates on `AnnData` objects and by default writes output back to these objects.
-   [X] The code is publicly available under an [OSI-approved](https://opensource.org/licenses/alphabetical) license
-   [X] The package provides versioned releases
-   [X] The package can be installed from a standard registry (e.g. PyPI, conda-forge, bioconda)
-   [X] The package uses automated software tests and runs them via continuous integration (CI)
-   [X] The package …
=> Add maxspin

packages/omicverse/meta.yaml
Name of the tool: omicverse
Short description: A python framework library for multi omics included bulk and single cell analysis with Python.
How does the package use scverse data structures (please describe in a few sentences): Designed to handle the analysis of transcriptomics, omicverse uses anndata as the basic data structure, derived in single-cell analysis using scanpy as the underlying framework.
-   [x] The package provides API …
=> add omicverse

packages/rapids-singlecell/meta.yaml
Name of the tool: rapids-singlecell
Short description: rapids-singlecell is a python package for GPU accelerated single cell data anaylsis
How does the package use scverse data structures (please describe in a few sentences): 
RSC uses AnnData as its datastructure and provides near dropin replacements for *scanpy*. It uses the plotting API of *scanpy*
-   [x] The package provides API documentation via a website or README
-   [x] The …
=> rapids-singlecell

scripts/src/ecosystem_scripts/template_repo_registry.py
It took me a little to figure out what this was and why it was in this repository. See also https://github.com/scverse/ecosystem-packages/issues/118
=> Clarify what template_repo_registry.py file does

README.md
I noticed we didn't tag any authors in the last round of announcements, but think it would be good to. I think this clarification may get more people to provide this info.
I also updated the language a little to account for the possibility of multiple authors.
=> Clarify how handles are provided

packages/favapy/meta.yaml
=> favapy package

.pre-commit-config.yaml, scripts/pyproject.toml
=> Switch to ruff formatting

packages/CellphoneDB/meta.yaml
_Name of the tool:_ CellphoneDB
_Short description:_ CellPhoneDB can be used to search for a particular ligand/receptor, or interrogate your own HUMAN single-cell transcriptomics data.
- The code is publicly available under an [OSI-approved](https://opensource.org/licenses/) license
- Yes, [https://opensource.org/license/mit/](https://opensource.org/license/mit/)
- The package provides versioned releases
- Yes, see: [https://github.com/ventolab/CellphoneDB/tags](https://github.com/ventolab/CellphoneDB/tags)
- The package can be installed from a standard registry (e.g. PyPI, conda-forge, bioconda)
- Yes, see [https://pypi.org/project/CellphoneDB/](https://pypi.org/project/CellphoneDB/)
- The package uses automated software tests and runs them via continuous integration (CI)
- Yes, see: …
=> New package config for CellphoneDB

packages/Rectangle/meta.yaml
Name of the tool: Rectangle
Short description: 
Rectangle presents a novel approach to second-generation deconvolution, characterized by hierarchical processing, an estimation of unknown cellular content and a significant reduction in data volume during signature matrix computation.
How does the package use scverse data structures (please describe in a few sentences): 
The package uses AnnData data structures to handle scRNA‐seq datasets, which are used to create marker gene signatures. 
-   [x] The package uses automated software …
=> Added meta.yaml for the Rectangle package

packages/scLiTr/meta.yaml
Name of the tool: scLiTr
Short description: scLiTr (**s**ingle-**c**ell **Li**neage **Tr**acing) is a Python package for exploratory analysis of barcoding-based scRNA-Seq lineage tracing experiments
How does the package use scverse data structures (please describe in a few sentences): it relies on AnnData during the construction of clonal embeddings (results of clone2vec algorithm) as well as matrices with Shapley values (to identify gene expression predictors of clonal behaviour).
- Bluesky: @sergeyisaev.bsky.social
- Twitter: @sv_isaev
=> Add a new package: scLiTr
